properties/array.py

Array properties still take `schema` in the same form as before, but now instead of looping through all the arrays, validation just does a quick numpy check to make sure the array matches the schema.

Change array validation from slow recursive check to quick numpy check

---

properties/base.py

This is a small change in how property sphinx docs appear that helps with intersphinx linking. Without these changes steno3dpy sphinx docs still work, the links just aren't all active.

Additional code to allow intersphinx linking to property doc

---

.bumpversion.cfg
properties/__init__.py
properties/array.py
properties/basic.py
properties/vmath/plane.py
tests/__init__.py

I allowed some type conversion to validate the schema in arrays. This is good for floats, I think (eg, ints get converted to floats), but not good for ints (floats shouldn't get converted to ints).

Make arrays less lenient for schema types

---

properties/base.py

Handle the case when the properties metaclass is called directly (as w/ `type`), and is given a unicode string as the new class name in Python 2.7.

Handle unicode class name in Python 2.7

---

properties/basic.py
tests/test_basic.py

String properties now are more friendly to unicode. The `unicode` attribute was added to String properties. By default this is true and all strings are coerced to unicode. If false, input string type will be maintained.
See: https://github.com/3ptscience/properties/issues/57

Improve treatment of unicode by String property

---

properties/basic.py
tests/test_basic.py

- StringChoice property attribute `choices` may now be a set in addition to list, tuple, or dict.
- If `choices` is a list or tuple, a `TypeError` will be raised if there are any repeated entries.
- If `choices` is a dictionary, a `TypeError` will be raised if there are any duplicate entries across all keys and values.
- Also dictionary values may now be tuples or sets in addition to lists
See: https://github.com/3ptscience/properties/issues/51

Allow sets and enforce uniqueness in string choices

---

properties/base.py
tests/test_basic.py

Introduces `_doc_order`, a list of all property names on a HasProperties class. This order will determine the order of the properties in the docs. After the docs are written, `_doc_order` is removed from the class dictionary.
Notes:
- `_doc_order` must contain ALL property names or be unspecified/empty. Otherwise an `AttributeError` will be raised on class definition.
- If `_doc_order` is not specified, the docs will be ordered alphabetically.
- `Required`/`Optional`/`Immutable` hierarchy in the docs supersedes `_doc_order`; the order will only be reflected within those sections.
See: https://github.com/3ptscience/properties/issues/58

Allow ordering of parameters in the docs

---

properties/base.py
properties/basic.py

All this does is described in the title. Hopefully there are very few external references to either of these. The reasoning for this is to remove the name conflict with builtin `help`.

Rename help/helpdoc to doc

---

properties/basic.py
tests/test_basic.py

This allows using numpy float/int/complex types for example that are not
subclasses of builtin float/int/etc without importing numpy.
See: #86

Validate floats, ints, and complex by casting, checking value, and catching errors.

---

properties/math.py
tests/test_math.py

Numpy arrays full of `object`s are now checked against the allowed `dtype`. 
Passing such an array to a new `Array` now fails the validation.

Fix Array validation

---

README.rst

I don't want to admit how long it took me to find the API docs, only to find that they were also in the GitHub project description.
With that in mind I think the docs should be in the ReadMe as well, so this PR adds a `Documentation` section under scope. I didn't see any other good spots for it, although maybe just adding the note in `Examples` section would be better.
* Add link to documentation on ReadTheDocs into ReadMe

[IMP] ReadMe: Add docs link

---

properties/base.py
properties/basic.py
properties/images.py
properties/math.py
tests/test_basic.py

1. The biggest change in this PR is renaming `info_text` to `class_info` and making `info` a property rather than a method. Both `info_text` and `info()` were directly copied from traitlets, and I think the former is not descriptive and the latter has no reason to not be a property. This change was made in a backwards compatible way so `Property` classes defined the old way will still be fine and just raise a warning. This change will have a minor effect on SimPEG. (see #104)
2. Error messages have been improved when `instance is None`. (see #98)
3. Property attributes have all been moved to property getters/setters. Most were this way, but some (eg `Union` `props`, `Instance` `instance_class`, etc) were not. (see #115)
4. `Instance` properties now support old-style classes (ie classes …

Clean up attribute setters, info, error messages

---

properties/basic.py
tests/test_basic.py

Add regular expression attribute strings must comply with. If `None` (default), any string is accepted.

regexp attribute for String properties

---

properties/basic.py
properties/task/image.py
tests/test_basic.py

As discussed in #103 
This also cleans up a few other things in StringChoice:
- `choices` order is preserved if possible using `OrderedDict`
- if `_choices` is somehow deleted, accessing `choices` will error, rather than default to `{}`
- make `choices` duplicate check case-insensitive ~since validation is case-insensitive~ unless new `case_sensitive` attribute is `True`.

Add `descriptions` attribute to StringChoice

---

.travis.yml
LICENSE
docs/conf.py
properties/__init__.py
properties/base.py
properties/basic.py
properties/utils.py
tests/test_recursion.py

This creates a wrapper for functions that runs the function once and gives an alternative return value if the same function is called again recursively. This prevents infinite recursion during validation and serialization.

Fix infinite recursion problems with validation/serialization

---

properties/__init__.py
properties/base.py
properties/basic.py
properties/math.py
properties/utils.py
tests/test_basic.py
tests/test_default.py
tests/test_dynamic.py
tests/test_instance.py
tests/test_list.py
tests/test_math.py
tests/test_recursion.py
tests/test_serialization.py
tests/test_union.py

This is currently used with `assert_valid` to ensure property values were not modified in a way that skipped validation.
- This lays the groundwork for a new listener that only fires on changes rather than every time it is set

Implement `equal` method for properties

---

properties/__init__.py
properties/base.py
properties/handlers.py
tests/test_basic.py
tests/test_handlers.py
tests/test_list.py
tests/test_serialization.py

- Introduce `observer` kwarg to only fire on change, rather than set
- Define `equal` method, rather than trying to override `__eq__` - the latter created lots of problems with hashing etc.
- `Set` and `Tuple` property types.

Modifications to some new features

---

docs/content/hasproperties.rst
properties/__init__.py
properties/base/base.py
properties/base/instance.py
properties/basic.py
tests/test_basic.py
tests/test_container.py
tests/test_serialization.py

This PR introduces `properties.copy` to copy a HasProperties instance. It simply serializes an instance then deserializes to a new instance. Also moves `HasProperties.equal` to `properties.equal` without modifying the functionality.
At a higher-lever, this sets a precedent for keeping `HasProperties` namespace as clean as possible so the properties are very accessible.

copy and equal functions

---

properties/base/base.py
properties/basic.py
properties/handlers.py
tests/test_basic.py
tests/test_math.py

Since `properties.Property.equal` simply used `==` it could return an array of booleans given certain input type (eg. numpy array). This fix now causes `properties.Property.equal` to return a single bool if `==` returns an iterable.
This PR also includes a bit of constraint on `equal` and change notification input. Namely `None`/`properties.undefined` should never be passed to `equal`, and `properties.undefined` will be used as `previous` and `value` in the change notification dictionary if no value is defined (as opposed to `None`).

Fix properties.Property.equal bug

---

properties/base/base.py
tests/test_basic.py

This removes the restriction against private properties. By default, these properties are undocumented, but they may be added to the docs with the `_doc_private = True` class attribute.
This PR also slightly modifies `_doc_order` - this attribute is now kept on the class and may be used for subclasses if their properties do not change.

Allow private properties

---

.travis.yml

It looks like python 3.6 is passing, and since it is becoming much more standard, the testing could enforce that properties passes on 3.6 as well.

python 3.6 in testing

---

docs/content/primitive.rst
docs/content/serialization.rst
properties/__init__.py
properties/basic.py
tests/test_basic.py

Adds a simple alias for backwards compatibility

Deprecate Bool in favor of Boolean

---

properties/base/containers.py
tests/test_container.py
tests/test_default.py

Using empty containers as defaults caused big problems and was not consistent with the rest of `properties` (see #169). This PR is not backwards compatible, but I think it is the right choice.

Remove _class_default from containers

---

docs/content/container.rst
properties/base/containers.py
tests/test_container.py

For example, previously if you used an `OrderedDict` for a `properties.Dictionary`, it would be coerced to a `dict`. Now, these classes are maintained.
Container classes still do not allow duck-typing - i.e. you still have to use a subclass of `dict`, not just something that implements `__getitem__`, `__setitem__`, etc.
This addresses @bsmithyman's comment here: https://github.com/aranzgeo/properties/pull/188#pullrequestreview-87918784

Non-standard container classes are now maintained

---

properties/base/base.py
properties/base/union.py
properties/extras/singleton.py
tests/test_serialization.py
tests/test_union.py

Deserializing when a `Union` of `Instance` properties is present results in unwanted behavior. `'__class__'` was ignored even when that class was a valid choice, and dictionaries were filtered to be empty to match one class, rather than selecting a different class.
Now, `deserialize` has additional kwargs:
- `strict` - this requires `__class__` to match the deserialized instance AND disallows extra properties in the input dictionary
- `assert_valid` - deserialization fails if the resulting instance is invalid.
To maintain backwards compatibility, both of these are `False` by default, but to fix the above `Union` bugs, they are `True` by default when deserializing the `Union` property. You can keep the current, lenient behavior of `Union` properties by setting `strict_instances=True` on …

Fix bugs that arise from deserializing dicts with Unions of Instance properties

---

docs/conf.py
properties/math.py

Related to this issue: https://github.com/gmggroup/omf/issues/43

Fix slow vector3array validation

---

docs/conf.py
properties/math.py
tests/test_math.py

Previously, `properties.Array` input was always coerced using the `Array.wrapper` attribute. However, this resulted in some funny behaviour with arrays being copied - see #272 
With this PR, there's now an optional `coerce` attribute on the array property. The default is `True` - in that case behaviour is unchanged. If this is False, though, the coerce step will be skipped, and input must start out as the valid type.

Add coerce as an argument to array property

---

properties/base/base.py
tests/test_basic.py

Some Mixins sometimes don't want to be `HasProperties` subclasses (since we need to mix them with other meta classes, eg ABC)
in these cases however we still want the properties defined here to show up in `_props` of base classes.
This fix rather than checking that the item class is a `HasProperties` subclass it checks if the item class is an instance of `PropertyMetaclass`.

Support Mixins that use the PropertyMetaclass
